In [79]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [80]:
import numpy as np

In [81]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
a[0]

1

In [83]:
a[3]

4

In [84]:
a[2:5]

array([3, 4, 5])

In [85]:
a[3:5]

array([4, 5])

In [86]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [87]:
a[-1]

10

In [88]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [89]:
a[-5:-1]

array([6, 7, 8, 9])

In [90]:
np.size(a)

10

In [91]:
np.shape(a)

(10,)

In [92]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:

a[0,0]

1

In [94]:
a[1,:]

array([4, 5, 6])

In [95]:
a[:,-1]

array([3, 6, 9])

In [96]:
a[:,0] = 1
a

array([[1, 2, 3],
       [1, 5, 6],
       [1, 8, 9]])

In [97]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])
np.size(a,0)

4

In [98]:
np.size(a,1)

3

In [99]:

np.ndim(a)

2

In [100]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [101]:
np.array(np_mix_matrix[:,1], dtype = int)

array([2, 4, 6])

In [102]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [103]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [104]:
c = np.full((2,2),8)
c

array([[8, 8],
       [8, 8]])

In [105]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

เอกลักษ์

In [106]:
c*d

array([[8., 0.],
       [0., 8.]])

In [107]:
2*np.ones((2,2))

array([[2., 2.],
       [2., 2.]])

In [108]:
np.sqrt(np.full((2,2),4))

array([[2., 2.],
       [2., 2.]])

สแควรูท

In [109]:
np.empty([5,5])

array([[0.e+000, 5.e-324, 1.e-323, 0.e+000, 5.e-324],
       [1.e-323, 0.e+000, 5.e-324, 1.e-323, 0.e+000],
       [5.e-324, 1.e-323, 0.e+000, 5.e-324, 1.e-323],
       [0.e+000, 5.e-324, 1.e-323, 0.e+000, 5.e-324],
       [1.e-323, 0.e+000, 5.e-324, 1.e-323, 0.e+000]])

In [110]:
np.random.rand()

0.11157090420347582

In [111]:
np.random.randint(5)

0

In [112]:
np.random.seed(4)
np.random.rand()

0.9670298390136767

seed = กำหนด pattern

In [113]:
np.random.rand(5,5)

array([[0.54723225, 0.97268436, 0.71481599, 0.69772882, 0.2160895 ],
       [0.97627445, 0.00623026, 0.25298236, 0.43479153, 0.77938292],
       [0.19768507, 0.86299324, 0.98340068, 0.16384224, 0.59733394],
       [0.0089861 , 0.38657128, 0.04416006, 0.95665297, 0.43614665],
       [0.94897731, 0.78630599, 0.8662893 , 0.17316542, 0.07494859]])

In [114]:
np.round(np.random.rand(5,5))

array([[1., 0., 1., 0., 1.],
       [1., 1., 0., 0., 1.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 0., 1.],
       [1., 0., 1., 1., 1.]])

In [115]:
np.round(np.random.rand(5,5)*1000)

array([[363., 638., 191., 498., 182.],
       [918., 432., 830., 417., 905.],
       [405., 331., 572., 845., 861.],
       [596.,  85., 597., 245., 733.],
       [895., 515., 604.,  65., 540.]])

EX.1

In [116]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([1, 9, 8, 6, 8])

สุ่ม แต่อาจซ้ำ

In [117]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace = False)

array([6, 2, 3, 8, 1])

สุ่ม แบบไม่ซ้ำ

In [118]:
np_matrix = np.random.rand(5,5)
idx_choose = np.random.choice(5,3)
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose


array([[0.96767963, 0.32061564, 0.8857971 , 0.54537692, 0.37110618],
       [0.13692582, 0.11251033, 0.07228326, 0.19323909, 0.0029266 ],
       [0.83113543, 0.78675315, 0.68964411, 0.65044111, 0.93729148]])

idx_choose = np.random.choice(5,3) สุ่ม 0-4 มา 3 ตัว
np_matrix_choose = np_matrix[idx_choose,:] สุ่มตาม idx_choose 

# EX.2

In [119]:

np_matrix = np.random.rand(10,5)
a = np.round(np_matrix[:,-1])
np_matrix[:,-1] = a
np_matrix

array([[0.14546233, 0.30879456, 0.75321209, 0.75535939, 1.        ],
       [0.93168902, 0.09014173, 0.19530471, 0.56146847, 0.        ],
       [0.2298969 , 0.03686156, 0.08438242, 0.66230243, 1.        ],
       [0.72686302, 0.90437662, 0.01671766, 0.89669186, 1.        ],
       [0.61481945, 0.13474565, 0.47196807, 0.63456949, 0.        ],
       [0.93141427, 0.93589384, 0.49996145, 0.40963549, 1.        ],
       [0.51577168, 0.48968914, 0.87039214, 0.89809177, 0.        ],
       [0.72955459, 0.56534436, 0.89098774, 0.31627651, 1.        ],
       [0.27923194, 0.11957669, 0.22698102, 0.77397163, 1.        ],
       [0.65072508, 0.30741661, 0.99740399, 0.29463256, 1.        ]])

In [120]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 5,  6,  6,  1,  0],
       [ 5,  2,  0,  5,  8],
       [ 5,  7,  8, 10,  9],
       [ 9,  0,  3,  7,  0],
       [ 4,  7,  7,  4,  1]])

สุ่มเลข 0-10 มาขนาด 5x5

In [121]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[0, 0, 1, 2, 1],
       [2, 1, 2, 0, 0],
       [1, 0, 0, 1, 2],
       [2, 1, 1, 2, 2],
       [2, 2, 2, 2, 0]])

In [122]:
i,j = np.where(np_matrix == 2)

หาตำแหน่ง i,j ที่มีค่าเป็น 2

In [123]:
i

array([0, 1, 1, 2, 3, 3, 3, 4, 4, 4, 4])

In [124]:
j

array([3, 0, 2, 4, 0, 3, 4, 0, 1, 2, 3])

# EX3

In [125]:
idx = [1,2,3,4]
np_matrix[idx,:]

array([[2, 1, 2, 0, 0],
       [1, 0, 0, 1, 2],
       [2, 1, 1, 2, 2],
       [2, 2, 2, 2, 0]])

In [126]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

array([[0, 0, 1, 2, 1],
       [2, 1, 1, 2, 2],
       [2, 2, 2, 2, 0]])

ลบแถวที่ 1,2  #0 = แถว #1 = colume

In [127]:
np_matrix = np.random.randint(10,size = (5,5))
np_matrix

array([[9, 1, 2, 9, 0],
       [6, 8, 5, 7, 5],
       [8, 1, 2, 3, 0],
       [5, 5, 6, 6, 0],
       [9, 5, 5, 3, 5]])

In [128]:
result = (np_matrix == 2)
result

array([[False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

หาค่า 2 ให้มีค่าเป็น True

In [129]:
np_matrix[result] = 99
np_matrix

array([[ 9,  1, 99,  9,  0],
       [ 6,  8,  5,  7,  5],
       [ 8,  1, 99,  3,  0],
       [ 5,  5,  6,  6,  0],
       [ 9,  5,  5,  3,  5]])

เปลี่ยน 2 เป็น 99

# EX4

In [130]:
np_matrix = np.random.randint(10,size = (10,5))
rabel_vector = np.random.randint(2,size = (10,))

In [131]:
np_matrix

array([[9, 1, 1, 9, 8],
       [1, 9, 1, 0, 6],
       [0, 0, 2, 8, 9],
       [0, 2, 9, 1, 5],
       [3, 5, 7, 3, 6],
       [9, 5, 8, 3, 6],
       [4, 4, 2, 8, 5],
       [7, 6, 2, 8, 4],
       [2, 6, 1, 0, 4],
       [9, 0, 7, 9, 0]])

In [132]:
rabel_vector

array([0, 0, 1, 1, 0, 0, 1, 1, 1, 1])

In [133]:
train_data = (rabel_vector == 0)
np_matrix[train_data]

array([[9, 1, 1, 9, 8],
       [1, 9, 1, 0, 6],
       [3, 5, 7, 3, 6],
       [9, 5, 8, 3, 6]])

In [134]:
test_data = (rabel_vector == 1)
np_matrix[test_data]

array([[0, 0, 2, 8, 9],
       [0, 2, 9, 1, 5],
       [4, 4, 2, 8, 5],
       [7, 6, 2, 8, 4],
       [2, 6, 1, 0, 4],
       [9, 0, 7, 9, 0]])

In [135]:
data = np.random.randint(5,size=(5,5)) + 1
data

array([[1, 3, 5, 1, 4],
       [5, 2, 4, 2, 1],
       [1, 3, 1, 5, 2],
       [4, 4, 2, 3, 5],
       [2, 4, 4, 2, 4]])

สุ่ม 0-4 มา +1

In [136]:
np.max(data)

5

ค่ามากสุดใน data

In [137]:
np.max(data,0)

array([5, 4, 5, 5, 5])

1. หาค่ามากที่สุดในแต่ละ colume #0 เป็น column แล้ว

In [138]:
np.max(data,1)

array([5, 5, 5, 5, 4])

หาค่ามากที่สุดในแต่ละ colume #1 เป็น row แล้ว

In [139]:
np.sum(data)

74

In [140]:
np.average(data)

2.96

In [141]:
data[0,:]

array([1, 3, 5, 1, 4])

ข้อมูลจาก row 0 มาทุก column

In [142]:
np.argmax(data[0,:])

2

หาตำแหน่งที่มากที่สุด จาก row 0 มาทุก column 

In [143]:
np.argmin(data[0,:])

0

หาตำแหน่งที่น้อยที่สุด จาก row 0 มาทุก column 

In [144]:
np.sort(data[0,:])

array([1, 1, 3, 4, 5])

เรียงจากน้อยไปมาก

In [145]:
np.argsort(data[0,:])

array([0, 3, 1, 4, 2])

เรียงตำแหน่งของเลขที่น้อย ไปมาก

# EX5

In [146]:
-np.sort(-data[0,:])


array([5, 4, 3, 1, 1])

In [147]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

1-10 ห่างที่ละ 2

In [148]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

5-10 แบ่งเป็น 10 ส่วน

In [149]:
data = np.round(np.random.random((5,5))*3)
data

array([[2., 2., 0., 1., 3.],
       [3., 3., 1., 3., 2.],
       [3., 0., 3., 1., 0.],
       [0., 1., 3., 1., 3.],
       [2., 1., 2., 1., 2.]])

In [150]:
data.shape

(5, 5)

In [151]:
data.reshape(1,25)

array([[2., 2., 0., 1., 3., 3., 3., 1., 3., 2., 3., 0., 3., 1., 0., 0.,
        1., 3., 1., 3., 2., 1., 2., 1., 2.]])

In [152]:
a = [[1,2],
        [3,4]]
a

[[1, 2], [3, 4]]

In [153]:
np.tile(a,(4,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

เพิ่ม a มา 4 row

In [154]:
np_test= np.arange(25).reshape(5,5)
result = (np_test % 3 == 0)
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# EX6

In [155]:
np_test[result]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

# EX7

In [156]:
np_test[np.fill_diagonal(np_test,0)]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  0,  7,  8,  9],
        [10, 11,  0, 13, 14],
        [15, 16, 17,  0, 19],
        [20, 21, 22, 23,  0]]])